{% set name = "argopandas" %}
{% set version = "0.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/argopandas-{{ version }}.tar.gz
  sha256: 0507de8ad3db60f9be39ec76ad6a79cb1f07da3a7dd630b34fde995d570a47ad

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - netcdf4
    - numpy
    - pandas
    - pyarrow
    - python >={{ python_min }}

test:
  imports:
    - argopandas
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/paleolimbot/argopandas
  summary: Locate, Download, and Read Argo Ocean Float Data
  license: MIT
  license_file: LICENSE
  doc_url: https://argocanada.github.io/argopandas/

extra:
  recipe-maintainers:
    - paleolimbot
